CREATE TABLE EMP(
	EID INT,
	ENAME VARCHAR(50),
	DEPARTMENT VARCHAR(500),
	SALARY INT,
	JOININGDATE DATETIME,
	CITY VARCHAR(50)
);

INSERT INTO EMP VALUES (101,'Rahul','Admin',56000,'1990-01-01','Rajkot')
INSERT INTO EMP VALUES (102,'Hardik','IT',18000,'1990-09-25','Ahmedabad')
INSERT INTO EMP VALUES (103,'Bhavin','HR',25000,'1991-05-14','Baroda')
INSERT INTO EMP VALUES (104,'Bhoomi','Admin',39000,'1991-02-08','Rajkot')
INSERT INTO EMP VALUES (105,'Rohit','IT',17000,'1990-07-23','Jamnagar')
INSERT INTO EMP VALUES (106,'Priya','IT',9000,'1990-10-18','Ahmedabad')
INSERT INTO EMP VALUES (107,'Bhoomi','HR',34000,'1991-12-25','Rajkot')

SELECT * FROM EMP

SELECT MAX(SALARY) AS MAXIMUM_SALARY, MIN(SALARY) AS MINIMUN_SALARY FROM EMP

SELECT COUNT(SALARY) AS TOTAL_SALARY,AVG(SALARY) AS AVG_SALARY FROM EMP

SELECT COUNT(EID) AS TOTOAL_EMP FROM EMP

SELECT MAX(SALARY) AS MAX_SALARY FROM EMP
WHERE CITY = 'RAJKOT'

SELECT MAX(SALARY) AS MAX_SALARY FROM EMP
WHERE DEPARTMENT = 'IT' 

SELECT COUNT(EID) FROM EMP
WHERE JOININGDATE > '1991-2-8'

SELECT SUM(SALARY) FROM EMP
WHERE DEPARTMENT = 'HR'

SELECT AVG(SALARY) AS AVG_SALARY FROM EMP
WHERE DEPARTMENT = 'ADMIN'

SELECT COUNT(DISTINCT CITY) FROM EMP


SELECT COUNT(DISTINCT DEPARTMENT) FROM EMP 

SELECT MIN(SALARY) FROM EMP 
WHERE CITY = 'AHMEDABAD'

SELECT CITY,MAX(SALARY) FROM EMP 
GROUP BY CITY

SELECT DEPARTMENT,MAX(SALARY) FROM EMP 
GROUP BY DEPARTMENT 

SELECT COUNT(EID) FROM EMP 
GROUP BY CITY

SELECT SUM(SALARY) AS TOTAL_SALARY FROM EMP 
GROUP BY DEPARTMENT

SELECT AVG(SALARY) FROM EMP 
GROUP BY DEPARTMENT

SELECT COUNT(EID) FROM EMP
WHERE CITY = 'RAJKOT' 

SELECT MAX(SALARY)-MIN(SALARY) AS DIFF FROM EMP

	





