




ALTER TABLE DEPOSIT
ADD CITY VARCHAR(50),PINCODE INT

SELECT *FROM DEPOSIT

ALTER TABLE DEPOSIT
ALTER COLUMN CNAME VARCHAR(35)

ALTER TABLE DEPOSIT
ALTER COLUMN AMOUNT INT

SP_RENAME 'DEPOSIT.ACTNO','ANO','COLUMN';

ALTER TABLE DEPOSIT
DROP COLUMN CITY

SP_RENAME DEPOSIT,DEPOSIT_DETAILS;

SP_RENAME 'DEPOSIT_DETAILS.ADATE','AOPENDATE','COLUMN';

ALTER TABLE DEPOSIT_DETAILS
DROP COLUMN AOPENDATE

SP_RENAME 'DEPOSIT_DETAILS.CNAME','CUSTOMERNAME','COLUMN';
