CREATE TABLE STUDENT_DATA(
NO INT,
NAME VARCHAR(50),
CITY VARCHAR(50),
DID INT
)

INSERT INTO STUDENT_DATA VALUES(101,'RAJU','RAJKOT',10)
INSERT INTO STUDENT_DATA VALUES(102,'AMIT','AHMEDABAD',20)
INSERT INTO STUDENT_DATA VALUES(103,'SANJAY','BARODA',40)
INSERT INTO STUDENT_DATA VALUES(104,'NEHA','RAJKOT',20)
INSERT INTO STUDENT_DATA VALUES(105,'MEERA','AHMEDABAD',30)
INSERT INTO STUDENT_DATA VALUES(106,'MAHESH','BARODA',10)

SELECT * FROM STUDENT_DATA

CREATE TABLE ACADEMIC(
	RNO INT,
	SPI FLOAT,
	BKLOG INT,
)

INSERT INTO ACADEMIC VALUES(101,8.8,0)
INSERT INTO ACADEMIC VALUES(102,9.2,2)
INSERT INTO ACADEMIC VALUES(103,7.6,1)
INSERT INTO ACADEMIC VALUES(104,8.2,4)
INSERT INTO ACADEMIC VALUES(105,7.0,2)
INSERT INTO ACADEMIC VALUES(106,8.9,3)

SELECT * FROM ACADEMIC

CREATE TABLE DEPARTMENT(
	DID INT,
	DNAME VARCHAR(10)
)

INSERT INTO DEPARTMENT VALUES(10,'COMPUTER')
INSERT INTO DEPARTMENT VALUES(20,'ELECTRICAL')
INSERT INTO DEPARTMENT VALUES(30,'MECHANICAL')
INSERT INTO DEPARTMENT VALUES(40,'CIVIL')

SELECT * FROM DEPARTMENT


------------------------------------------------------------------
--PART A
--1
SELECT NAME FROM STUDENT_DATA
WHERE DID=(SELECT DID FROM DEPARTMENT WHERE DNAME='COMPUTER') 

--2
SELECT NAME FROM STUDENT_DATA 
WHERE NO IN (SELECT RNO FROM ACADEMIC WHERE SPI>8)

--3
TRUNCATE TABLE STUDENT_DATA

SELECT * FROM STUDENT_DATA 
WHERE DID = (SELECT DID FROM DEPARTMENT WHERE DNAME='COMPUTER') AND CITY='RAJKOT'

--4
SELECT COUNT(NO) FROM STUDENT_DATA
WHERE DID=(SELECT DID FROM DEPARTMENT WHERE DNAME='ELECTRICAL')

--5
SELECT NAME FROM STUDENT_DATA 
WHERE NO IN
(SELECT RNO FROM ACADEMIC WHERE SPI =
(SELECT MAX(SPI) FROM ACADEMIC))

--6
SELECT NAME FROM STUDENT_DATA
WHERE NO IN (SELECT RNO FROM ACADEMIC WHERE BKLOG>1)

--PART B
--1
SELECT NAME FROM STUDENT_DATA
WHERE DID 
IN (SELECT DID FROM DEPARTMENT WHERE DNAME='COMPUTER' OR
DNAME='MECHANICAL')

--2
SELECT NAME FROM STUDENT_DATA
WHERE DID IN (SELECT DID FROM DEPARTMENT WHERE 
DID IN(SELECT DID FROM DEPARTMENT WHERE DNAME='ELECTRICAL'))

--PART C
--1
SELECT NAME FROM  STUDENT_DATA
WHERE NO IN (SELECT RNO FROM ACADEMIC  WHERE SPI>9) AND  DID=(SELECT DID FROM DEPARTMENT WHERE DNAME ='ELECTRICAL')

--2
SELECT name
FROM STUDENT_DATA
WHERE spi = (
    SELECT MAX(spi)
    FROM ACADEMIC
    WHERE spi < (
        SELECT MAX(spi)
        FROM ACADEMIC
    )
);


--3
SELECT CITY FROM STUDENT_DATA
WHERE NO= 
(SELECT RNO FROM ACADEMIC WHERE SPI = 9.2) 
AND 
DID IN (SELECT DID FROM DEPARTMENT WHERE DNAME IN (SELECT DNAME FROM DEPARTMENT GROUP BY DNAME))

--SET OPERATOR
--PART A
CREATE TABLE COMPUTER(
	ROLLNO INT,
	NAME VARCHAR(20)
);
 
 INSERT INTO COMPUTER VALUES(101,'AJAY')
 INSERT INTO COMPUTER VALUES(109,'HARESH')
 INSERT INTO COMPUTER VALUES(115,'MANISH')

 SELECT * FROM COMPUTER

 CREATE TABLE ELECTRICAL(
	ROLLNO INT,
	NAME VARCHAR(20)
 );

 INSERT INTO ELECTRICAL VALUES(105,'AJAY'),
							  (107,'MAHESH'),
							  (115,'MANISH')
SELECT * FROM ELECTRICAL

--1
SELECT Name FROM COMPUTER
UNION
SELECT Name FROM ELECTRICAL;

--2
SELECT Name FROM COMPUTER
UNION ALL
SELECT Name FROM ELECTRICAL;

--3
SELECT Name FROM COMPUTER
INTERSECT
SELECT Name FROM ELECTRICAL;

--4
SELECT Name FROM COMPUTER
EXCEPT
SELECT Name FROM ELECTRICAL;

--5
SELECT Name FROM ELECTRICAL
EXCEPT
SELECT Name FROM COMPUTER;

--6
SELECT * FROM COMPUTER
UNION ALL
SELECT * FROM ELECTRICAL;

--7
SELECT * FROM COMPUTER
INTERSECT
SELECT * FROM ELECTRICAL;


-----------Part - B:----------
CREATE TABLE EMP_DATA(
		EID INT,
		NAME VARCHAR(20)
	);

INSERT INTO EMP_DATA VALUES (1,'AJAY'),
							(9,'HARESH'),
							(5,'MANISH')

CREATE TABLE CUSTOMER(
		CID INT,
		NAME VARCHAR(20)
	);

INSERT INTO CUSTOMER VALUES (5,'AJAY'),
							(7,'MAHESH'),
							(5,'MANISH')

--1
SELECT NAME FROM EMP_DATA
UNION
SELECT NAME FROM CUSTOMER

--2
SELECT NAME FROM EMP_DATA
UNION ALL
SELECT NAME FROM CUSTOMER

--3
SELECT NAME FROM EMP_DATA
INTERSECT
SELECT NAME FROM CUSTOMER

--4
SELECT NAME FROM EMP_DATA
EXCEPT
SELECT NAME FROM CUSTOMER

--5
SELECT NAME FROM CUSTOMER
EXCEPT
SELECT NAME FROM EMP_DATA

----------------Part - C:-----------------

--1
SELECT NAME, EID FROM EMP_DATA
UNION
SELECT NAME, CID FROM CUSTOMER

--2
SELECT NAME,EID FROM EMP_DATA
UNION ALL
SELECT NAME,CID FROM CUSTOMER

--3
SELECT NAME,EID FROM EMP_DATA
INTERSECT
SELECT NAME,CID FROM CUSTOMER

--4
SELECT NAME,EID FROM EMP_DATA
EXCEPT
SELECT NAME,CID FROM CUSTOMER

--5
SELECT NAME,CID FROM CUSTOMER
EXCEPT
SELECT NAME,EID FROM EMP_DATA







































